### ISSUE TITLE
Exception when calling uidgen.generateSync()

### ISSUE THREAD

**Issue by StefanGussner** [nwoltman/node-uid-generator#1]
where uidgen is 
`const uidgen = new UIDGenerator(null,UIDGenerator.BASE62,50);`

```
TypeError: Cannot read property '_bufferToString' of undefined
    at generateSync (/node_modules/uid-generator/index.js:72:17)
...
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
return this._bufferToString(crypto.randomBytes(this._byteSize));
```
(this is undefined)

**Comment by nwoltman** [comment]
Looks like you're doing something like this:

```js
const generateSync = uidgen.generateSync;

// ...

generateSync(); // Error
```

`uidgen` is a class instance so you need to call `generateSync()` on it directly:

```js
uidgen.generateSync();
```

**Comment by StefanGussner** [comment]
oh thx :)

**Comment by nwoltman** [comment]
No problem :)
